### ISSUE TITLE
Caused by: java.net.UnknownHostException: db

### ISSUE THREAD

**Issue by locmansueto** [cucpbioinfo/STRategy#2]
Hi any recommendation on specific mysql tag?
Getting this exception in the backend at start up

Caused by: com.mysql.cj.jdbc.exceptions.CommunicationsException: Communications link failure

The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.
        at com.mysql.cj.jdbc.exceptions.SQLError.createCommunicationsException(SQLError.java:174) ~[mysql-connector-java-8.0.21.jar:8.0.21]
..
Caused by: java.net.UnknownHostException: db
        at java.base/java.net.InetAddress$CachedAddresses.get(InetAddress.java:800) ~[na:na]

**Comment by soncomqiq** [comment]
@locmansueto 

Hi, apologies for the late reply.

It seems the issue might be related to the MySQL container not being fully started when the backend attempts to connect.

To confirm that the MySQL container (named `db`) is running successfully, you can:
1. Run the command `docker ps` in your terminal to check the status of your containers.
2. Alternatively, if you’re using Docker Desktop, check the "Containers" tab to ensure the `db` container is up and running.

If you’re still encountering issues, feel free to provide more details, and I’ll be happy to assist further!
